management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
    #show-details: always
  endpoints:
    web:
      exposure:
        include: "*"